development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: simpl_development
  pool: 5
  timeout: 5000

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: simpl_test
  pool: 5
  timeout: 5000

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: simpl
  pool: 5
  timeout: 5000